[package]
name = "discord_clone"
version = "0.1.0"
authors = ["Dawid33 <dawidso6467@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[lib]
name = "discord_clone_lib"
path = "src/lib/lib.rs"