refersh_rate_miliseconds = 50
url = "ws://localhost:9001/socket"
use_tui = true

[key_map]
quit = "q"
help = "?"
left = "h"
right = "l"
resize_left = "H"
resize_right = "L"
up = "j"
down = "k"
reload_config = "r"

[ui_config]
background_color = [0, 0, 0]
default_urls = ["file:///home/dawids/Projects/rust/logfile-watcher-rs/latest.log"]